services:
  game:
    image: 192.168.200.19:443/serveur-puissance4:latest
    ports:
      - 6000:6000
      - 6001:6001
  game2:
    image: 192.168.200.19:443/client-puissance4:latest
    ports:
      - 6002:6002
    environment:
      - IP_ADRESSE_SERVEUR=192.168.200.16
      - PORT_SERVEUR=6000
